name: Build

on:
  pull_request:
    types: [ opened, reopened ]
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.100'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Restore
        run: |
          dotnet restore
          
      - name: Build
        run: |
          dotnet build --no-restore

